version: "3"
services:
  node-app:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - mongo
  
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lalo
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
